version: '3'

services:
  oracle:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      oracle-network:
        ipv4_address: 172.29.0.8
    ports:
      - "8080:8080"
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://172.29.0.8:8080/metrics",
            "namespace": "oracle",
            "metrics": [
              {"oracle_block_submissions_total": "block_submissions_total"},
            ]
          }
        ]



  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DD_KEY}
      - DD_TAGS=env:test
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    # ports:
    #   - "5000:5000"
    networks:
      oracle-network:
          ipv4_address: 172.29.0.9


networks:
  oracle-network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
