version: '3.8'

services:
  oracle:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
    restart: always
    environment:
      - L1_URL=http://54.191.222.69:8545
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit_oracle*",
              "go*"
            ]
          }
        ]
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"

  oracle-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: oracle_db
      POSTGRES_USER: oracle_user
      POSTGRES_PASSWORD: oracle_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
